---
title: Syntax Reference
email: your-email@domain.com
description: A programming language reference.
baseurl: ''
url: http://yourdomain.com
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
host: 0.0.0.0
languages:
- name: Ruby
  highlight: ruby
  extension: rb
- name: C++
  highlight: cpp
  extension: cpp
- name: C#
  highlight: cs
  extension: cs
syntax_samples:
- title: If Else Then
  snippet: if
- title: Comments
  snippet: comments
- title: Program Structure
  snippet: program_structure
- title: File Input
  snippet: file_input
- title: Arrays
  snippet: arrays
